### ISSUE TITLE
LoweringModeDropdown text does not update after selection

### ISSUE THREAD

**Issue by rgov** [WHOIGit/ndsf-sealog-client#26]
In the LoweringGallery component, for example, selecting a new lowering via the LoweringModeDropdown causes the page to change but the label in the upper left to stay the same.

This shouldn't use `this.state` at all but should probably call back to the parent to update the lowering prop and re-render.

**Comment by mcschwartzman** [comment]
Resolved April 18, 2023 at 2:40 PM by @mcschwartzman (SL-29)
