### ISSUE TITLE
Clean up FREE_FORM / Free Text in UI

### ISSUE THREAD

**Issue by rgov** [WHOIGit/ndsf-sealog-client#31]
We don't want this ugly label everywhere, it should be simplified to just show the text.

**Comment by mcschwartzman** [comment]
@ahimahis What do you think of this? Got rid of the redundant second "free_text". The remaining "FREE_FORM" is of course the event type
![image](https://user-images.githubusercontent.com/26795373/211086549-09523213-5c5f-4bc3-9dc1-5204be6d5cc6.png)

**Comment by mcschwartzman** [comment]
Personally I prefer the above, but if you'd like I can hack that out so that **you only see the event type if it's NOT a free_form event**
![image](https://user-images.githubusercontent.com/26795373/211087771-4430ca67-9a86-4c1b-aabb-054a1c0844e7.png)

**Comment by rgov** [comment]
The `-->` ASCII arrow is a little goofy and we don't need the quotation marks either. If you were to redesign the list from scratch, what would you choose to show?

What about a table with aligned columns?

**Comment by mcschwartzman** [comment]
Yeah I definitely want a table here, but I want to abstract out the list item first as it's defined in like 3 places (that i've found so far). There's a bit of refactoring I want to do before redesigning too much XD

**Comment by rgov** [comment]
Definitely. One idea also is that those comment buttons can appear on hover with a little bit of CSS or JS to spare the visual noise.
