### ISSUE TITLE
Display position delta between realtime and renav in nav card

### ISSUE THREAD

**Issue by rgov** [WHOIGit/ndsf-sealog-client#32]
James would like to export it in the JSON as well.

To be determined:

* Include Z in delta?
* Just do L2 norm or show delta for each dimension?

**Comment by mcschwartzman** [comment]
Looking at this now. I'd like to tweak this to see all nav data displayed in columns in 1 card, with little badges/headers at the top that indicate data source, like:

         Original | Delta | Renav
lat        123       2          125
long     456       3          459

**Comment by rgov** [comment]
Could work. Chat with @ahimahis and Vicki about this one, they had mockups for the nav card that I followed.

**Comment by mcschwartzman** [comment]
Copy. Problem right now is AFAICT the data-card code works by rendering a card for EACH aux-data-object.

**Comment by webbpinner** [comment]
you may want to take a look at the upstream client code: https://github.com/OceanDataTools/sealog-client-vehicle/blob/2.x/src/components/lowering_replay.js

This problem has been encountered on multiple installs so I added an exclude mechanism so that aux_data types are ignored by the standard card mechanism in favor of a bespoke render.

**Comment by rgov** [comment]
Yes, the basic design of Sealog is that each data source (like the frame grabber, or real time nav) attaches one aux data object to an event. Then the Sealog web client renders one card per aux data object.

A big exception is the `reorganizeNavData()` function (which exists in our version, not upstream) which combines the aux data objects for realtime and renav into one, according to the spec.

https://github.com/WHOIGit/ndsf-sealog-client/blob/311c85f851d7d1dcfe90806ceedc33452b79f208/src/components/event_preview.js#L46

A change from upstream in our version is also that you can override the card rendering per data source, which we've also done in the nav card, which basically generates a multi-column table:

https://github.com/WHOIGit/ndsf-sealog-client/blob/311c85f851d7d1dcfe90806ceedc33452b79f208/src/components/data_cards/nav_card.js

**Comment by mcschwartzman** [comment]
Resolved May 30, 2023 at 4:49 PM by @mcschwartzman (SL-27)
