### ISSUE TITLE
Make it better to type into Tweak Milestones date fields

### ISSUE THREAD

**Issue by rgov** [WHOIGit/ndsf-sealog-client#35]

**Comment by mcschwartzman** [comment]
cruise tn406 -> lowering   1438 -> replay 

system admin-> lowerings -> 1438 -> edit -> milestones and stats -> tweak milestones (they don't like the arrows)

ALSO everytime you edit the milestones it gets duplicated

**Comment by mcschwartzman** [comment]
Resolved May 30, 2023 at 1:11 PM by @figuernd
