### ISSUE TITLE
Lowering start/stop time validation is annoying

### ISSUE THREAD

**Issue by rgov** [WHOIGit/ndsf-sealog-client#37]
It gets in the way of setting up a new lowering because you have to set up the stop time first.

**Comment by mcschwartzman** [comment]
@rgov Just gathering more info here. Is the issue reporter essentially to make the lowering stop time optional?

**Comment by rgov** [comment]
(Most of these bugs come via Tina if I'm not available to clarify.)

I think the issue is that when you start a lowering you probably don't know when it will end (especially for *Jason* which can be down for days at a time).

There's a form validator that checks that `startTime <= stopTime`. It appears that it silently prevents you from creating/updating the lowering when this is violated by disabling the "Update" button, without telling you why.

Maybe an improvement would be:

1. When creating a lowering, after `startTime` is chosen but `stopTime` is still unset, pick a reasonable default. (Like 1 day in the future or something, maybe configurable in a setting?)

2. When the `startTime <= stopTime` validator fails, communicate this to the user.

**Comment by mcschwartzman** [comment]
Okay that all makes sense! Thanks!
