### ISSUE TITLE
Events with comments are not clearly labeled in lowering_replay

### ISSUE THREAD

**Issue by mcschwartzman** [WHOIGit/ndsf-sealog-client#41]
@ahimahis described illustrated that currently the only unique sign that an event has a comment is a slight change in the "add comment" button.

Note: This is especially an issue for users who use the comment button to "correct" previously logged events (as users cannot edit events).

**Comment by mcschwartzman** [comment]
@ahimahis  
![image](https://user-images.githubusercontent.com/26795373/220423180-e5e03fad-2235-42c2-8a8c-b637ca8a938c.png)

**Comment by jogarcia-whoi** [comment]
Hi, @ahimahis. I wanted to bump this, have you had a chance to look at it?
